version: "3.9"
services:
  mobilecap:
    image: ${OPENCAP_IMAGE_NAME}
    volumes:
      - data:/data
    env_file:
      - ../.env
    environment:
      - DOCKERCOMPOSE=1
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              capabilities: [gpu]
              device_ids: ["${INSTANCE_ID}"]
    cpuset: "${CPU_SET}"
    logging:
      driver: "json-file"
      options:
        max-size: "100m"  # Rotate when the log reaches 10MB
        max-file: "7"    # Keep the last 7 log files
  openpose:
    image: ${OPENPOSE_IMAGE_NAME}
    volumes:
      - data:/openpose/data
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              capabilities: [gpu]
              device_ids: ["${INSTANCE_ID}"]
    cpuset: "${CPU_SET}"
    logging:
      driver: "json-file"
      options:
        max-size: "100m"  # Rotate when the log reaches 10MB
        max-file: "7"    # Keep the last 7 log files
    restart: on-failure:3
  mmpose:
    image: ${MMPOSE_IMAGE_NAME}
    volumes:
      - data:/mmpose/data
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              capabilities: [gpu]
              device_ids: ["${INSTANCE_ID}"]
    cpuset: "${CPU_SET}"
    logging:
      driver: "json-file"
      options:
        max-size: "100m"  # Rotate when the log reaches 10MB
        max-file: "7"    # Keep the last 7 log files
    restart: on-failure:3

volumes:
  data: {}
